export const initialState = {
  auth: {
    user: {
      id: '',
      firstName: '',
      lastName: '',
      email: '',
      createdAt: '',
      updatedAt: '',
    },
    accessToken: '',
    refreshToken: '',
    isAuthenticated: false,
    isCreatingAccount: false,
    isLoggingIn: false,
    isLoggingOut: false,
  },
  event: {
    events: [],
    activeEvent: {
      id: '',
      title: '',
      description: '',
      startsAt: '',
      capacity: 0,
      owner: {
        id: '',
        firstName: '',
        lastName: '',
        email: '',
        createdAt: '',
        updatedAt: '',
      },
      attendees: [],
      createdAt: '',
      updatedAt: '',
    },
    isFetchingEvent: false,
    isFetchingEvents: false,
    isCreatingEvent: false,
    isUpdatingEvent: false,
    isUpdatingAttendeeStatus: false,
    isDeletingEvent: false,
  },
};
